
GET http://localhost:5236/api/categories

###
POST http://localhost:5236/api/categories
Content-Type: application/json

{
    "name":"Electronic",
    "description":"Desvices and gaduets including phone, laptops and other electronic equipment"
}
###
PUT http://localhost:5236/api/categories

Content-Type: application/json
{
    "name":"Cloth",
    "description":"Desvices and gaduets including phone, laptops and other electronic equipment"
}

###
DELETE http://localhost:5236/api/categories
